### PR TITLE
Improving log of Apache2

### PR DESCRIPTION
**Pull request by glasswalk3r**
ErrorLog was defined twice for the same virtual host
Added custom fields to ErrorLogFormat
Removed commented configuration

### CODE REVIEW

**Comment by preaction** [comment]
In order for me to review the changes, I need to know why the changes are necessary. Removing the first instance of the `ErrorLog` directive makes sense to me, because it was being ignored and could lead to confusion if someone checked that log and saw nothing. But why add the `ErrorLogFormat`? Why remove the commented-out RewriteLog lines?

Please also see [this advice on how to write good commit messages](https://chris.beams.io/posts/git-commit/). It's about the same thing: The commit message should explain why this change is being made. The diff tells me what's changing (so the commit message does not need to say that), but can't tell me why (so the commit message must say).

**Comment by glasswalk3r** [comment]
> In order for me to review the changes, I need to know why the changes are necessary. Removing the first instance of the ErrorLog directive makes sense to me, because it was being ignored and could lead to confusion if someone checked that log and saw nothing. But why add the ErrorLogFormat? Why remove the commented-out RewriteLog lines?

My apologies. Here are the explanations:

- `ErrorLogFormat` addition: when I noticed the server was presenting issues to produce the tests reports page, I had trouble to find out what kind of request was failing, so I could try to reproduce it. The addition of it was to try to provide more information for troubleshooting.
- `RewriteLog` removal: in the same sense of not maintaining commented code in source code, for the sake of clarity. If it is commented, it is not being used. If it is not being used, it shouldn't be there. On the other hand, I could be more explicit in the commit stating that I "removed RewriteLog entries that were commented".

**Comment by preaction** [comment]
This isn't source code, though. This is a configuration file. Often there are going to be bits left commented-out for easy re-enabling in crises. In a crisis, I'm not going to be here in this git repository looking for lost bits of configuration in the revision history, I'm going to be logged-on to the server and editing things by hand.

This one is fine: I never use the RewriteLog unless I know I need it, and at that point I'm probably deep in the documentation anyway. But there's no need to go around deleting configuration lines, even commented-out ones, unless everyone's certain they don't have any value.

**Comment by preaction** [comment]
Merged via command-line

**Pull request closed without merging**
